# Creates HORIZON Docker STACK
name: "horizon"
services:
  postgres:
    image: "postgres:16-alpine"
    container_name: "horizon_db"
    restart: always
    ports:
      - "5432:5432"
    networks:
      - horizon_network
    volumes:
      - ${POSTGRES_DATA:?required}:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER:?required}
      POSTGRES_PASSWORD: ${POSTGRES_PASS?:required}
      POSTGRES_DB: horizon
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $$POSTGRES_DB -U $$POSTGRES_USER"]
      interval: 1s
      timeout: 5s
      retries: 10
  spring:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
      no_cache: true
    image: "horizon/spring-backend"
    container_name: "horizon_be"
    restart: unless-stopped
    ports:
      - "${PORT}:8080"
    depends_on:
      - postgres
    environment:
      DATASOURCE_JDBC: "jdbc:postgresql://horizon_db:5432/horizon"
      DATASOURCE_USER: ${POSTGRES_USER}
      DATASOURCE_PASS: ${POSTGRES_PASS}
      CORS_ORIGINS: ${CORS_ORIGINS:?required}
      CORS_HEADERS: ${CORS_HEADERS:?required}
    networks:
      - horizon_network
networks:
  horizon_network:
    name: horizon_network
    driver: bridge