# Creates development Database
name: "horizon_dev"
services:
  postgres:
    image: "postgres:16-alpine"
    container_name: "horizon_dev_postgres"
    restart: always
    ports:
      - "5431:5432"
    networks:
      - horizon_dev_network
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: horizon_user
      POSTGRES_PASSWORD: horizon_pass
      POSTGRES_DB: horizon
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $$POSTGRES_DB -U $$POSTGRES_USER"]
      interval: 1s
      timeout: 5s
      retries: 10
volumes:
  postgres_data:
    name: horizon_dev_data
networks:
  horizon_dev_network:
    name: horizon_dev_network
    driver: bridge